### PR TITLE
Task : added index.html

### PR DESCRIPTION
**Pull request by devmusiczz**

### CODE REVIEW

**Comment by devmusiczz** [comment]
fix #1

**Comment by DcodeZw3** [comment]
Add some stylings and try to give a Heading "Custom-openID-Auth"
stylings include a centered div with the heading and the website should be dark themed
the 2 input fields should also be styled and contain placeholders (username and password)
the buttons should be styled green and have border radius in em

**Comment by devmusiczz** [comment]
alright.

**Comment by DcodeZw3** [comment]
Verified!

**Pull request merged**
